# install.packages('readxl')
# install.packages("dplyr")
# install.packages('tidyr')
# install.packages("stringr")
# install.packages('openxlsx')
# install.packages('rlang')
# install.packages("readxl")
#install.packages("ggplot2")
#install.packages("scales")
#install.packages("feather", repos ="https://cloud.r-project.org")
#install.packages("SmartEDA", repos ="https://cloud.r-project.org")

library(readxl)
library(dplyr)
library(tidyr)
library(rlang)
library(openxlsx)
library(stringr)
# library(scales)
# library(feather)
# library(arrow)